In [54]:
import numpy as np
     
train_x = np.random.rand(10000,5)    
test_x = np.random.rand(10000,5)    

print(train_x)
print(test_x)

[[0.99573987 0.69762188 0.48087123 0.60618523 0.74167554]
 [0.43753399 0.90785415 0.60229339 0.8187805  0.8791958 ]
 [0.74491676 0.5688165  0.21039556 0.97917144 0.0445037 ]
 ...
 [0.8860165  0.68291477 0.8321408  0.39689626 0.8291024 ]
 [0.58063383 0.8998279  0.27078815 0.64661522 0.00385573]
 [0.10251952 0.94930385 0.40706273 0.82637332 0.12241743]]
[[0.88021615 0.10643578 0.51495286 0.99374429 0.44929739]
 [0.7786871  0.51357875 0.1348097  0.14493085 0.82964932]
 [0.78455215 0.12719098 0.14902295 0.59890773 0.53158193]
 ...
 [0.079832   0.7187326  0.43348176 0.95343745 0.1545103 ]
 [0.18151399 0.69391536 0.44414765 0.76183479 0.17723941]
 [0.42445515 0.77262296 0.24891463 0.21800541 0.38955884]]


In [55]:
def prepare(data):
    avg = np.average(data, axis = 1)
    ret = np.append(data, np.reshape(avg, (-1, 1)), axis=1 )
    return ret


In [56]:
train = prepare(train_x)
test = prepare(test_x)

print(train)
print(test)

[[0.99573987 0.69762188 0.48087123 0.60618523 0.74167554 0.70441875]
 [0.43753399 0.90785415 0.60229339 0.8187805  0.8791958  0.72913156]
 [0.74491676 0.5688165  0.21039556 0.97917144 0.0445037  0.50956079]
 ...
 [0.8860165  0.68291477 0.8321408  0.39689626 0.8291024  0.72541415]
 [0.58063383 0.8998279  0.27078815 0.64661522 0.00385573 0.48034416]
 [0.10251952 0.94930385 0.40706273 0.82637332 0.12241743 0.48153537]]
[[0.88021615 0.10643578 0.51495286 0.99374429 0.44929739 0.5889293 ]
 [0.7786871  0.51357875 0.1348097  0.14493085 0.82964932 0.48033114]
 [0.78455215 0.12719098 0.14902295 0.59890773 0.53158193 0.43825115]
 ...
 [0.079832   0.7187326  0.43348176 0.95343745 0.1545103  0.46799882]
 [0.18151399 0.69391536 0.44414765 0.76183479 0.17723941 0.45173024]
 [0.42445515 0.77262296 0.24891463 0.21800541 0.38955884 0.4107114 ]]


In [57]:
np.savetxt('train.csv', train, delimiter=',', header="1, 2, 3, 4, 5, avg", comments="")
np.savetxt('test.csv', test, delimiter=',', header="1, 2, 3, 4, 5, avg", comments="")